# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/monitor_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonitorWidget(object):
    def setupUi(self, MonitorWidget):
        MonitorWidget.setObjectName("MonitorWidget")
        MonitorWidget.resize(729, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(MonitorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_topic_name = QtWidgets.QLineEdit(MonitorWidget)
        self.edit_topic_name.setObjectName("edit_topic_name")
        self.horizontalLayout.addWidget(self.edit_topic_name)
        self.button_add_topic = QtWidgets.QPushButton(MonitorWidget)
        self.button_add_topic.setObjectName("button_add_topic")
        self.horizontalLayout.addWidget(self.button_add_topic)
        self.button_save_monitor = QtWidgets.QPushButton(MonitorWidget)
        self.button_save_monitor.setObjectName("button_save_monitor")
        self.horizontalLayout.addWidget(self.button_save_monitor)
        self.button_load_monitor = QtWidgets.QPushButton(MonitorWidget)
        self.button_load_monitor.setObjectName("button_load_monitor")
        self.horizontalLayout.addWidget(self.button_load_monitor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_topics_values = QtWidgets.QTableView(MonitorWidget)
        self.table_topics_values.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table_topics_values.setObjectName("table_topics_values")
        self.table_topics_values.horizontalHeader().setDefaultSectionSize(300)
        self.table_topics_values.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table_topics_values)

        self.retranslateUi(MonitorWidget)
        QtCore.QMetaObject.connectSlotsByName(MonitorWidget)

    def retranslateUi(self, MonitorWidget):
        _translate = QtCore.QCoreApplication.translate
        MonitorWidget.setWindowTitle(_translate("MonitorWidget", "Form"))
        self.edit_topic_name.setToolTip(_translate("MonitorWidget", "Topic name"))
        self.button_add_topic.setText(_translate("MonitorWidget", "Add topic"))
        self.button_save_monitor.setText(_translate("MonitorWidget", "Save monitor"))
        self.button_load_monitor.setText(_translate("MonitorWidget", "Load monitor"))
