# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/structure_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StructureWidget(object):
    def setupUi(self, StructureWidget):
        StructureWidget.setObjectName("StructureWidget")
        StructureWidget.resize(452, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(StructureWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_topic_name = QtWidgets.QLineEdit(StructureWidget)
        self.edit_topic_name.setObjectName("edit_topic_name")
        self.horizontalLayout_2.addWidget(self.edit_topic_name)
        self.button_print = QtWidgets.QPushButton(StructureWidget)
        self.button_print.setObjectName("button_print")
        self.horizontalLayout_2.addWidget(self.button_print)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tree_topic_fields = QtWidgets.QTreeView(StructureWidget)
        self.tree_topic_fields.setObjectName("tree_topic_fields")
        self.tree_topic_fields.header().setDefaultSectionSize(300)
        self.verticalLayout.addWidget(self.tree_topic_fields)

        self.retranslateUi(StructureWidget)
        QtCore.QMetaObject.connectSlotsByName(StructureWidget)

    def retranslateUi(self, StructureWidget):
        _translate = QtCore.QCoreApplication.translate
        StructureWidget.setWindowTitle(_translate("StructureWidget", "Form"))
        self.edit_topic_name.setToolTip(_translate("StructureWidget", "Topic name"))
        self.button_print.setText(_translate("StructureWidget", "Print structure"))
