# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/topics_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopicsWidget(object):
    def setupUi(self, TopicsWidget):
        TopicsWidget.setObjectName("TopicsWidget")
        TopicsWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TopicsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_filter = QtWidgets.QLineEdit(TopicsWidget)
        self.edit_filter.setObjectName("edit_filter")
        self.horizontalLayout.addWidget(self.edit_filter)
        self.button_filter = QtWidgets.QPushButton(TopicsWidget)
        self.button_filter.setObjectName("button_filter")
        self.horizontalLayout.addWidget(self.button_filter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_topics = QtWidgets.QListView(TopicsWidget)
        self.list_topics.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list_topics.setObjectName("list_topics")
        self.verticalLayout.addWidget(self.list_topics)
        self.button_refresh = QtWidgets.QPushButton(TopicsWidget)
        self.button_refresh.setObjectName("button_refresh")
        self.verticalLayout.addWidget(self.button_refresh)

        self.retranslateUi(TopicsWidget)
        QtCore.QMetaObject.connectSlotsByName(TopicsWidget)

    def retranslateUi(self, TopicsWidget):
        _translate = QtCore.QCoreApplication.translate
        TopicsWidget.setWindowTitle(_translate("TopicsWidget", "Form"))
        self.button_filter.setText(_translate("TopicsWidget", "Filter"))
        self.button_refresh.setText(_translate("TopicsWidget", "Refresh"))
